# Generated by Django 3.0.7 on 2020-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitesettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Free_Shipping_Threshold', models.DecimalField(blank=True, db_column='Free Shipping Threshold', decimal_places='2', default='50.00', max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
