# Generated by Django 3.0.7 on 2020-12-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='Free_Shipping_Threshold',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.CharField(blank=True, default='Free Shipping Treshold', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default='50.00', max_digits=5, null=True),
        ),
    ]
