# Generated by Django 3.0.7 on 2020-12-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20201221_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='free_shipping_threshold',
            new_name='name',
        ),
    ]
