# Generated by Django 3.0.7 on 2020-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20201221_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
