# Generated by Django 3.0.7 on 2020-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_sitesettings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
