# Generated by Django 3.0.7 on 2020-12-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201223_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True)),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
