# Generated by Django 3.0.7 on 2020-12-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_sitestats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestats',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='sitestats',
            name='value',
        ),
        migrations.AddField(
            model_name='sitestats',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
