# Generated by Django 3.0.7 on 2020-12-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201230_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestats',
            name='date',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
