# Generated by Django 3.0.7 on 2020-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_sitestats_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestats',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
