# Generated by Django 3.1.4 on 2021-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20201230_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='available',
            field=models.BooleanField(blank=True, choices=[(True, 'Available'), (False, 'Unavailable')], default=True, null=True),
        ),
    ]
