# Generated by Django 3.0.7 on 2020-10-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='service_category',
            options={'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='booking_made',
        ),
        migrations.AddField(
            model_name='bookings',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='customer_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
