# Generated by Django 3.0.7 on 2020-10-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201017_0856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Category',
            new_name='serviceCategory',
        ),
    ]
