# Generated by Django 3.0.7 on 2020-12-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201017_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='customer_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='username',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
