# Generated by Django 3.0.7 on 2020-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20201219_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
