# Generated by Django 3.1.4 on 2021-01-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20201221_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='customer_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
