# Generated by Django 3.1.4 on 2021-01-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210105_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
