# Generated by Django 3.1.4 on 2021-01-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookings_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='staff',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
