# Generated by Django 3.1.4 on 2021-01-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bookings_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_id',
            field=models.CharField(default='', editable=False, max_length=254),
        ),
    ]
