# Generated by Django 3.1.4 on 2021-01-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookings_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
