# Generated by Django 3.0.7 on 2020-12-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201216_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Standard Shipping', max_length=50),
        ),
    ]
