# Generated by Django 3.0.7 on 2020-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='Standard Shipping', max_length=50, null=True),
        ),
    ]
