# Generated by Django 3.0.7 on 2020-12-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openhours',
            name='time',
        ),
        migrations.AddField(
            model_name='openhours',
            name='closingTime',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='openhours',
            name='openingTime',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
