# Generated by Django 3.0.7 on 2020-12-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201204_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='closingTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='openingTime',
            field=models.TimeField(null=True),
        ),
    ]
