# Generated by Django 3.0.7 on 2020-12-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201204_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='About Us', max_length='2000')),
            ],
            options={
                'verbose_name_plural': 'About Us Text',
            },
        ),
    ]
