# Generated by Django 3.0.7 on 2021-01-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_openhours_markedclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='markedClosed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
