# Generated by Django 3.0.7 on 2020-12-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
