# Generated by Django 3.0.7 on 2020-12-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_featured_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
