# Generated by Django 3.1.4 on 2021-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210109_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo_url',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
